// import aula1 from './aula1/index'
// import aula2 from './aula2/index'
// import aula3 from './aula3/index'
// import aula4 from './aula4/index'
// import aula5 from './aula5/index'
import aula6 from './aula6/index'